env:
  global:
  - secure: UyhJm7fJ8RoP6LCfTjuudZogLlc6TA60DlJFS8MaJ76v8EVw9al54a7laYmLP8Ez94NLj33xwkGXx4jI3HcvZ4i8RS+R3KObCsGQHo0SmtxHtiQsiQ9vdSqjY9bccowhzuc6tZ7MpZBzkxiAjL3zNDmgyLy4ZQo0yHghTGAsuabpUuDm3UhkfPmvHZq9MM/lJLp6etkgLqYKi+fVC9Ir2GfGnPdaDsc6JFfbKnNH7X7fS9mJ6MSyUwYs6L/QcE3f73OtzACJWwukso8gtUdLLCM90iZQydQv/6W1rLce8lEONffUA6pfPKVAdLHKgJ707WGcjPPRROzMAM6GrKZcBel22Vy1MhYTXfZzon8XeIRRkFDCU821J3enf7Qs1Xq4nGBp+PJmW60MENlW4LjI1BbRqE0il2UtxFTPZ7dExGVpKJu//CQLfQTJAKTB3CD9eLEFKNu1Z/wKfVl7ahbgC11XNrmwHm8VU+JA8UiQkv3zpFZaR08ZZdXKrwTlTiqKI8QgmGv0htVnKqgLE2EiuyxviXC9BPPfzuGLLeNHXahPWF8BtUOvgEOHCRG6uAEzbrXsvIPY6cFmwbRmoHsI+TZ4bjQVi6tXf1qu9hs8MNWTuT6OJUxATg5yN8IOHU3s86Gxy3nl92oD0TNkS1I3rB44tRt6b/ctwSNnNdsmWeI=
  - secure: uK+SrpMu4H5+tbrZ3Css/a9NQFdTjGFR6213y1ZwAvLuvV73EsL99ZDO07FrgWj4KJ4w0mzXfSqNeHfuBzpCZxXIS2L2V97JvXlCVKjU8yrLEPU6rghmVn+npBIHulAKx9dQv2Yj0u6+HB0Kg8+H4HBtWpqziYvaEVbnGd6nVgfoyc/nbduzeZ5NqhLvccfE5U086ei7Eq6BpFYVh80TwvUmuHxFpotw1IT9xh5Q4xuklYcJNzhmT/fDT7/1mjPps9KK1EgGI8cS9VfrcH3Kv/Q/0Y6+OxmSeO9UPGiVOnihx8QkATZDKmiowZfcIAjSbC6Ulw0uHIUc96p/tLm4juQGHv87iBbGJJ71oZUEaf+p02thvr/OuqTmueo1uB3e9vyK3rhaluv8REwboTckq+z+Pm8EvXd8PtQR8wDvm8drGvSON774xgJihBimoUsdQhnPP7eJqvDUIPoqxcg5dJ23nUaDrF4mtnwow/PyD6AAxgTNy2JYf60BrT/oM2EIh+eNE5+VRymb8WIyvWbTYuIMLveyAWNxhRWLDm3FmI4iNPULl7FG9EZWYhMVPBhdo2bOWL/yAkmEjyfaTVy75Soh23vUs6fg6BdDwnqsJZfbuasMd/rvsGL+3pLgPxDFoDrB7enp6+JxC6vj93mEcRK3N+grCa+BQFYoLiWA/HQ=
dist: trusty
sudo: required
addons:
  chrome: stable
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.6
    - python3-pip
language: node_js
services:
- docker
install:
- pip3 install --user awscli
script:
- docker-compose build
- docker tag thatbrothacodes-blog:1.9.0 826109606486.dkr.ecr.us-east-1.amazonaws.com/thatbrothacodes-blog:1.9.0
- eval $(aws ecr get-login --no-include-email)
- docker push 826109606486.dkr.ecr.us-east-1.amazonaws.com/thatbrothacodes-blog:1.9.0
- aws ecs register-task-definition --cli-input-json file://ecs-task-def.json
- aws ecs update-service --service thatbrothacodes-blog-service --task-definition thatbrothacodes-blog-task-def --cluster demo-web-apps